// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sentence.proto

package syntaxnet;

public final class SentenceOuterClass {
  private SentenceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SentenceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:syntaxnet.Sentence)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Identifier for document.
     * </pre>
     *
     * <code>string docid = 1;</code>
     */
    java.lang.String getDocid();
    /**
     * <pre>
     * Identifier for document.
     * </pre>
     *
     * <code>string docid = 1;</code>
     */
    com.google.protobuf.ByteString
        getDocidBytes();

    /**
     * <pre>
     * Raw text contents of the sentence.
     * </pre>
     *
     * <code>string text = 2;</code>
     */
    java.lang.String getText();
    /**
     * <pre>
     * Raw text contents of the sentence.
     * </pre>
     *
     * <code>string text = 2;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <pre>
     * Tokenization of the sentence.
     * </pre>
     *
     * <code>repeated .syntaxnet.Token token = 3;</code>
     */
    java.util.List<syntaxnet.SentenceOuterClass.Token> 
        getTokenList();
    /**
     * <pre>
     * Tokenization of the sentence.
     * </pre>
     *
     * <code>repeated .syntaxnet.Token token = 3;</code>
     */
    syntaxnet.SentenceOuterClass.Token getToken(int index);
    /**
     * <pre>
     * Tokenization of the sentence.
     * </pre>
     *
     * <code>repeated .syntaxnet.Token token = 3;</code>
     */
    int getTokenCount();
    /**
     * <pre>
     * Tokenization of the sentence.
     * </pre>
     *
     * <code>repeated .syntaxnet.Token token = 3;</code>
     */
    java.util.List<? extends syntaxnet.SentenceOuterClass.TokenOrBuilder> 
        getTokenOrBuilderList();
    /**
     * <pre>
     * Tokenization of the sentence.
     * </pre>
     *
     * <code>repeated .syntaxnet.Token token = 3;</code>
     */
    syntaxnet.SentenceOuterClass.TokenOrBuilder getTokenOrBuilder(
        int index);
  }
  /**
   * <pre>
   * A Sentence contains the raw text contents of a sentence, as well as an
   * analysis.
   * </pre>
   *
   * Protobuf type {@code syntaxnet.Sentence}
   */
  public  static final class Sentence extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:syntaxnet.Sentence)
      SentenceOrBuilder {
    // Use Sentence.newBuilder() to construct.
    private Sentence(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sentence() {
      docid_ = "";
      text_ = "";
      token_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Sentence(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              docid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                token_ = new java.util.ArrayList<syntaxnet.SentenceOuterClass.Token>();
                mutable_bitField0_ |= 0x00000004;
              }
              token_.add(
                  input.readMessage(syntaxnet.SentenceOuterClass.Token.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          token_ = java.util.Collections.unmodifiableList(token_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return syntaxnet.SentenceOuterClass.internal_static_syntaxnet_Sentence_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return syntaxnet.SentenceOuterClass.internal_static_syntaxnet_Sentence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              syntaxnet.SentenceOuterClass.Sentence.class, syntaxnet.SentenceOuterClass.Sentence.Builder.class);
    }

    private int bitField0_;
    public static final int DOCID_FIELD_NUMBER = 1;
    private volatile java.lang.Object docid_;
    /**
     * <pre>
     * Identifier for document.
     * </pre>
     *
     * <code>string docid = 1;</code>
     */
    public java.lang.String getDocid() {
      java.lang.Object ref = docid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        docid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Identifier for document.
     * </pre>
     *
     * <code>string docid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDocidBytes() {
      java.lang.Object ref = docid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        docid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object text_;
    /**
     * <pre>
     * Raw text contents of the sentence.
     * </pre>
     *
     * <code>string text = 2;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Raw text contents of the sentence.
     * </pre>
     *
     * <code>string text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private java.util.List<syntaxnet.SentenceOuterClass.Token> token_;
    /**
     * <pre>
     * Tokenization of the sentence.
     * </pre>
     *
     * <code>repeated .syntaxnet.Token token = 3;</code>
     */
    public java.util.List<syntaxnet.SentenceOuterClass.Token> getTokenList() {
      return token_;
    }
    /**
     * <pre>
     * Tokenization of the sentence.
     * </pre>
     *
     * <code>repeated .syntaxnet.Token token = 3;</code>
     */
    public java.util.List<? extends syntaxnet.SentenceOuterClass.TokenOrBuilder> 
        getTokenOrBuilderList() {
      return token_;
    }
    /**
     * <pre>
     * Tokenization of the sentence.
     * </pre>
     *
     * <code>repeated .syntaxnet.Token token = 3;</code>
     */
    public int getTokenCount() {
      return token_.size();
    }
    /**
     * <pre>
     * Tokenization of the sentence.
     * </pre>
     *
     * <code>repeated .syntaxnet.Token token = 3;</code>
     */
    public syntaxnet.SentenceOuterClass.Token getToken(int index) {
      return token_.get(index);
    }
    /**
     * <pre>
     * Tokenization of the sentence.
     * </pre>
     *
     * <code>repeated .syntaxnet.Token token = 3;</code>
     */
    public syntaxnet.SentenceOuterClass.TokenOrBuilder getTokenOrBuilder(
        int index) {
      return token_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDocidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, docid_);
      }
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
      }
      for (int i = 0; i < token_.size(); i++) {
        output.writeMessage(3, token_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDocidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, docid_);
      }
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
      }
      for (int i = 0; i < token_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, token_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof syntaxnet.SentenceOuterClass.Sentence)) {
        return super.equals(obj);
      }
      syntaxnet.SentenceOuterClass.Sentence other = (syntaxnet.SentenceOuterClass.Sentence) obj;

      boolean result = true;
      result = result && getDocid()
          .equals(other.getDocid());
      result = result && getText()
          .equals(other.getText());
      result = result && getTokenList()
          .equals(other.getTokenList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOCID_FIELD_NUMBER;
      hash = (53 * hash) + getDocid().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      if (getTokenCount() > 0) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getTokenList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static syntaxnet.SentenceOuterClass.Sentence parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static syntaxnet.SentenceOuterClass.Sentence parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(syntaxnet.SentenceOuterClass.Sentence prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A Sentence contains the raw text contents of a sentence, as well as an
     * analysis.
     * </pre>
     *
     * Protobuf type {@code syntaxnet.Sentence}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:syntaxnet.Sentence)
        syntaxnet.SentenceOuterClass.SentenceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return syntaxnet.SentenceOuterClass.internal_static_syntaxnet_Sentence_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return syntaxnet.SentenceOuterClass.internal_static_syntaxnet_Sentence_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                syntaxnet.SentenceOuterClass.Sentence.class, syntaxnet.SentenceOuterClass.Sentence.Builder.class);
      }

      // Construct using syntaxnet.SentenceOuterClass.Sentence.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTokenFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        docid_ = "";

        text_ = "";

        if (tokenBuilder_ == null) {
          token_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          tokenBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return syntaxnet.SentenceOuterClass.internal_static_syntaxnet_Sentence_descriptor;
      }

      public syntaxnet.SentenceOuterClass.Sentence getDefaultInstanceForType() {
        return syntaxnet.SentenceOuterClass.Sentence.getDefaultInstance();
      }

      public syntaxnet.SentenceOuterClass.Sentence build() {
        syntaxnet.SentenceOuterClass.Sentence result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public syntaxnet.SentenceOuterClass.Sentence buildPartial() {
        syntaxnet.SentenceOuterClass.Sentence result = new syntaxnet.SentenceOuterClass.Sentence(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.docid_ = docid_;
        result.text_ = text_;
        if (tokenBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            token_ = java.util.Collections.unmodifiableList(token_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.token_ = token_;
        } else {
          result.token_ = tokenBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof syntaxnet.SentenceOuterClass.Sentence) {
          return mergeFrom((syntaxnet.SentenceOuterClass.Sentence)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(syntaxnet.SentenceOuterClass.Sentence other) {
        if (other == syntaxnet.SentenceOuterClass.Sentence.getDefaultInstance()) return this;
        if (!other.getDocid().isEmpty()) {
          docid_ = other.docid_;
          onChanged();
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (tokenBuilder_ == null) {
          if (!other.token_.isEmpty()) {
            if (token_.isEmpty()) {
              token_ = other.token_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTokenIsMutable();
              token_.addAll(other.token_);
            }
            onChanged();
          }
        } else {
          if (!other.token_.isEmpty()) {
            if (tokenBuilder_.isEmpty()) {
              tokenBuilder_.dispose();
              tokenBuilder_ = null;
              token_ = other.token_;
              bitField0_ = (bitField0_ & ~0x00000004);
              tokenBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTokenFieldBuilder() : null;
            } else {
              tokenBuilder_.addAllMessages(other.token_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        syntaxnet.SentenceOuterClass.Sentence parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (syntaxnet.SentenceOuterClass.Sentence) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object docid_ = "";
      /**
       * <pre>
       * Identifier for document.
       * </pre>
       *
       * <code>string docid = 1;</code>
       */
      public java.lang.String getDocid() {
        java.lang.Object ref = docid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          docid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Identifier for document.
       * </pre>
       *
       * <code>string docid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDocidBytes() {
        java.lang.Object ref = docid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          docid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Identifier for document.
       * </pre>
       *
       * <code>string docid = 1;</code>
       */
      public Builder setDocid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        docid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Identifier for document.
       * </pre>
       *
       * <code>string docid = 1;</code>
       */
      public Builder clearDocid() {
        
        docid_ = getDefaultInstance().getDocid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Identifier for document.
       * </pre>
       *
       * <code>string docid = 1;</code>
       */
      public Builder setDocidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        docid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <pre>
       * Raw text contents of the sentence.
       * </pre>
       *
       * <code>string text = 2;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Raw text contents of the sentence.
       * </pre>
       *
       * <code>string text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Raw text contents of the sentence.
       * </pre>
       *
       * <code>string text = 2;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Raw text contents of the sentence.
       * </pre>
       *
       * <code>string text = 2;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Raw text contents of the sentence.
       * </pre>
       *
       * <code>string text = 2;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private java.util.List<syntaxnet.SentenceOuterClass.Token> token_ =
        java.util.Collections.emptyList();
      private void ensureTokenIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          token_ = new java.util.ArrayList<syntaxnet.SentenceOuterClass.Token>(token_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          syntaxnet.SentenceOuterClass.Token, syntaxnet.SentenceOuterClass.Token.Builder, syntaxnet.SentenceOuterClass.TokenOrBuilder> tokenBuilder_;

      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public java.util.List<syntaxnet.SentenceOuterClass.Token> getTokenList() {
        if (tokenBuilder_ == null) {
          return java.util.Collections.unmodifiableList(token_);
        } else {
          return tokenBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public int getTokenCount() {
        if (tokenBuilder_ == null) {
          return token_.size();
        } else {
          return tokenBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public syntaxnet.SentenceOuterClass.Token getToken(int index) {
        if (tokenBuilder_ == null) {
          return token_.get(index);
        } else {
          return tokenBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public Builder setToken(
          int index, syntaxnet.SentenceOuterClass.Token value) {
        if (tokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTokenIsMutable();
          token_.set(index, value);
          onChanged();
        } else {
          tokenBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public Builder setToken(
          int index, syntaxnet.SentenceOuterClass.Token.Builder builderForValue) {
        if (tokenBuilder_ == null) {
          ensureTokenIsMutable();
          token_.set(index, builderForValue.build());
          onChanged();
        } else {
          tokenBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public Builder addToken(syntaxnet.SentenceOuterClass.Token value) {
        if (tokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTokenIsMutable();
          token_.add(value);
          onChanged();
        } else {
          tokenBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public Builder addToken(
          int index, syntaxnet.SentenceOuterClass.Token value) {
        if (tokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTokenIsMutable();
          token_.add(index, value);
          onChanged();
        } else {
          tokenBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public Builder addToken(
          syntaxnet.SentenceOuterClass.Token.Builder builderForValue) {
        if (tokenBuilder_ == null) {
          ensureTokenIsMutable();
          token_.add(builderForValue.build());
          onChanged();
        } else {
          tokenBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public Builder addToken(
          int index, syntaxnet.SentenceOuterClass.Token.Builder builderForValue) {
        if (tokenBuilder_ == null) {
          ensureTokenIsMutable();
          token_.add(index, builderForValue.build());
          onChanged();
        } else {
          tokenBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public Builder addAllToken(
          java.lang.Iterable<? extends syntaxnet.SentenceOuterClass.Token> values) {
        if (tokenBuilder_ == null) {
          ensureTokenIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, token_);
          onChanged();
        } else {
          tokenBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public Builder clearToken() {
        if (tokenBuilder_ == null) {
          token_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          tokenBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public Builder removeToken(int index) {
        if (tokenBuilder_ == null) {
          ensureTokenIsMutable();
          token_.remove(index);
          onChanged();
        } else {
          tokenBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public syntaxnet.SentenceOuterClass.Token.Builder getTokenBuilder(
          int index) {
        return getTokenFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public syntaxnet.SentenceOuterClass.TokenOrBuilder getTokenOrBuilder(
          int index) {
        if (tokenBuilder_ == null) {
          return token_.get(index);  } else {
          return tokenBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public java.util.List<? extends syntaxnet.SentenceOuterClass.TokenOrBuilder> 
           getTokenOrBuilderList() {
        if (tokenBuilder_ != null) {
          return tokenBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(token_);
        }
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public syntaxnet.SentenceOuterClass.Token.Builder addTokenBuilder() {
        return getTokenFieldBuilder().addBuilder(
            syntaxnet.SentenceOuterClass.Token.getDefaultInstance());
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public syntaxnet.SentenceOuterClass.Token.Builder addTokenBuilder(
          int index) {
        return getTokenFieldBuilder().addBuilder(
            index, syntaxnet.SentenceOuterClass.Token.getDefaultInstance());
      }
      /**
       * <pre>
       * Tokenization of the sentence.
       * </pre>
       *
       * <code>repeated .syntaxnet.Token token = 3;</code>
       */
      public java.util.List<syntaxnet.SentenceOuterClass.Token.Builder> 
           getTokenBuilderList() {
        return getTokenFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          syntaxnet.SentenceOuterClass.Token, syntaxnet.SentenceOuterClass.Token.Builder, syntaxnet.SentenceOuterClass.TokenOrBuilder> 
          getTokenFieldBuilder() {
        if (tokenBuilder_ == null) {
          tokenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              syntaxnet.SentenceOuterClass.Token, syntaxnet.SentenceOuterClass.Token.Builder, syntaxnet.SentenceOuterClass.TokenOrBuilder>(
                  token_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          token_ = null;
        }
        return tokenBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:syntaxnet.Sentence)
    }

    // @@protoc_insertion_point(class_scope:syntaxnet.Sentence)
    private static final syntaxnet.SentenceOuterClass.Sentence DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new syntaxnet.SentenceOuterClass.Sentence();
    }

    public static syntaxnet.SentenceOuterClass.Sentence getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sentence>
        PARSER = new com.google.protobuf.AbstractParser<Sentence>() {
      public Sentence parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Sentence(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sentence> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sentence> getParserForType() {
      return PARSER;
    }

    public syntaxnet.SentenceOuterClass.Sentence getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:syntaxnet.Token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Token word form.
     * </pre>
     *
     * <code>string word = 1;</code>
     */
    java.lang.String getWord();
    /**
     * <pre>
     * Token word form.
     * </pre>
     *
     * <code>string word = 1;</code>
     */
    com.google.protobuf.ByteString
        getWordBytes();

    /**
     * <pre>
     * Start position of token in text.
     * </pre>
     *
     * <code>int32 start = 2;</code>
     */
    int getStart();

    /**
     * <pre>
     * End position of token in text. Gives index of last byte, not one past
     * the last byte. If token came from lexer, excludes any trailing HTML tags.
     * </pre>
     *
     * <code>int32 end = 3;</code>
     */
    int getEnd();

    /**
     * <pre>
     * Head of this token in the dependency tree: the id of the token which has an
     * arc going to this one. If it is the root token of a sentence, then it is
     * set to -1.
     * </pre>
     *
     * <code>int32 head = 4;</code>
     */
    int getHead();

    /**
     * <pre>
     * Part-of-speech tag for token.
     * </pre>
     *
     * <code>string tag = 5;</code>
     */
    java.lang.String getTag();
    /**
     * <pre>
     * Part-of-speech tag for token.
     * </pre>
     *
     * <code>string tag = 5;</code>
     */
    com.google.protobuf.ByteString
        getTagBytes();

    /**
     * <pre>
     * Coarse-grained word category for token.
     * </pre>
     *
     * <code>string category = 6;</code>
     */
    java.lang.String getCategory();
    /**
     * <pre>
     * Coarse-grained word category for token.
     * </pre>
     *
     * <code>string category = 6;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <pre>
     * Label for dependency relation between this token and its head.
     * </pre>
     *
     * <code>string label = 7;</code>
     */
    java.lang.String getLabel();
    /**
     * <pre>
     * Label for dependency relation between this token and its head.
     * </pre>
     *
     * <code>string label = 7;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <pre>
     *[default = SPACE_BREAK];
     * </pre>
     *
     * <code>.syntaxnet.Token.BreakLevel break_level = 8;</code>
     */
    int getBreakLevelValue();
    /**
     * <pre>
     *[default = SPACE_BREAK];
     * </pre>
     *
     * <code>.syntaxnet.Token.BreakLevel break_level = 8;</code>
     */
    syntaxnet.SentenceOuterClass.Token.BreakLevel getBreakLevel();
  }
  /**
   * <pre>
   * A document token marks a span of bytes in the document text as a token
   * or word.
   * </pre>
   *
   * Protobuf type {@code syntaxnet.Token}
   */
  public  static final class Token extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:syntaxnet.Token)
      TokenOrBuilder {
    // Use Token.newBuilder() to construct.
    private Token(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Token() {
      word_ = "";
      start_ = 0;
      end_ = 0;
      head_ = 0;
      tag_ = "";
      category_ = "";
      label_ = "";
      breakLevel_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Token(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              word_ = s;
              break;
            }
            case 16: {

              start_ = input.readInt32();
              break;
            }
            case 24: {

              end_ = input.readInt32();
              break;
            }
            case 32: {

              head_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              tag_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              category_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              label_ = s;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              breakLevel_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return syntaxnet.SentenceOuterClass.internal_static_syntaxnet_Token_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return syntaxnet.SentenceOuterClass.internal_static_syntaxnet_Token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              syntaxnet.SentenceOuterClass.Token.class, syntaxnet.SentenceOuterClass.Token.Builder.class);
    }

    /**
     * <pre>
     * Break level for tokens that indicates how it was separated from the
     * previous token in the text.
     * </pre>
     *
     * Protobuf enum {@code syntaxnet.Token.BreakLevel}
     */
    public enum BreakLevel
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * No separation between tokens.
       * </pre>
       *
       * <code>NO_BREAK = 0;</code>
       */
      NO_BREAK(0),
      /**
       * <pre>
       * Tokens separated by space.
       * </pre>
       *
       * <code>SPACE_BREAK = 1;</code>
       */
      SPACE_BREAK(1),
      /**
       * <pre>
       * Tokens separated by line break.
       * </pre>
       *
       * <code>LINE_BREAK = 2;</code>
       */
      LINE_BREAK(2),
      /**
       * <pre>
       * Tokens separated by sentence break.
       * </pre>
       *
       * <code>SENTENCE_BREAK = 3;</code>
       */
      SENTENCE_BREAK(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * No separation between tokens.
       * </pre>
       *
       * <code>NO_BREAK = 0;</code>
       */
      public static final int NO_BREAK_VALUE = 0;
      /**
       * <pre>
       * Tokens separated by space.
       * </pre>
       *
       * <code>SPACE_BREAK = 1;</code>
       */
      public static final int SPACE_BREAK_VALUE = 1;
      /**
       * <pre>
       * Tokens separated by line break.
       * </pre>
       *
       * <code>LINE_BREAK = 2;</code>
       */
      public static final int LINE_BREAK_VALUE = 2;
      /**
       * <pre>
       * Tokens separated by sentence break.
       * </pre>
       *
       * <code>SENTENCE_BREAK = 3;</code>
       */
      public static final int SENTENCE_BREAK_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BreakLevel valueOf(int value) {
        return forNumber(value);
      }

      public static BreakLevel forNumber(int value) {
        switch (value) {
          case 0: return NO_BREAK;
          case 1: return SPACE_BREAK;
          case 2: return LINE_BREAK;
          case 3: return SENTENCE_BREAK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BreakLevel>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          BreakLevel> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BreakLevel>() {
              public BreakLevel findValueByNumber(int number) {
                return BreakLevel.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return syntaxnet.SentenceOuterClass.Token.getDescriptor().getEnumTypes().get(0);
      }

      private static final BreakLevel[] VALUES = values();

      public static BreakLevel valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private BreakLevel(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:syntaxnet.Token.BreakLevel)
    }

    public static final int WORD_FIELD_NUMBER = 1;
    private volatile java.lang.Object word_;
    /**
     * <pre>
     * Token word form.
     * </pre>
     *
     * <code>string word = 1;</code>
     */
    public java.lang.String getWord() {
      java.lang.Object ref = word_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        word_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Token word form.
     * </pre>
     *
     * <code>string word = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWordBytes() {
      java.lang.Object ref = word_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        word_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_FIELD_NUMBER = 2;
    private int start_;
    /**
     * <pre>
     * Start position of token in text.
     * </pre>
     *
     * <code>int32 start = 2;</code>
     */
    public int getStart() {
      return start_;
    }

    public static final int END_FIELD_NUMBER = 3;
    private int end_;
    /**
     * <pre>
     * End position of token in text. Gives index of last byte, not one past
     * the last byte. If token came from lexer, excludes any trailing HTML tags.
     * </pre>
     *
     * <code>int32 end = 3;</code>
     */
    public int getEnd() {
      return end_;
    }

    public static final int HEAD_FIELD_NUMBER = 4;
    private int head_;
    /**
     * <pre>
     * Head of this token in the dependency tree: the id of the token which has an
     * arc going to this one. If it is the root token of a sentence, then it is
     * set to -1.
     * </pre>
     *
     * <code>int32 head = 4;</code>
     */
    public int getHead() {
      return head_;
    }

    public static final int TAG_FIELD_NUMBER = 5;
    private volatile java.lang.Object tag_;
    /**
     * <pre>
     * Part-of-speech tag for token.
     * </pre>
     *
     * <code>string tag = 5;</code>
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Part-of-speech tag for token.
     * </pre>
     *
     * <code>string tag = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_FIELD_NUMBER = 6;
    private volatile java.lang.Object category_;
    /**
     * <pre>
     * Coarse-grained word category for token.
     * </pre>
     *
     * <code>string category = 6;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Coarse-grained word category for token.
     * </pre>
     *
     * <code>string category = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_FIELD_NUMBER = 7;
    private volatile java.lang.Object label_;
    /**
     * <pre>
     * Label for dependency relation between this token and its head.
     * </pre>
     *
     * <code>string label = 7;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Label for dependency relation between this token and its head.
     * </pre>
     *
     * <code>string label = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BREAK_LEVEL_FIELD_NUMBER = 8;
    private int breakLevel_;
    /**
     * <pre>
     *[default = SPACE_BREAK];
     * </pre>
     *
     * <code>.syntaxnet.Token.BreakLevel break_level = 8;</code>
     */
    public int getBreakLevelValue() {
      return breakLevel_;
    }
    /**
     * <pre>
     *[default = SPACE_BREAK];
     * </pre>
     *
     * <code>.syntaxnet.Token.BreakLevel break_level = 8;</code>
     */
    public syntaxnet.SentenceOuterClass.Token.BreakLevel getBreakLevel() {
      syntaxnet.SentenceOuterClass.Token.BreakLevel result = syntaxnet.SentenceOuterClass.Token.BreakLevel.valueOf(breakLevel_);
      return result == null ? syntaxnet.SentenceOuterClass.Token.BreakLevel.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, word_);
      }
      if (start_ != 0) {
        output.writeInt32(2, start_);
      }
      if (end_ != 0) {
        output.writeInt32(3, end_);
      }
      if (head_ != 0) {
        output.writeInt32(4, head_);
      }
      if (!getTagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tag_);
      }
      if (!getCategoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, category_);
      }
      if (!getLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, label_);
      }
      if (breakLevel_ != syntaxnet.SentenceOuterClass.Token.BreakLevel.NO_BREAK.getNumber()) {
        output.writeEnum(8, breakLevel_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, word_);
      }
      if (start_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, start_);
      }
      if (end_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, end_);
      }
      if (head_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, head_);
      }
      if (!getTagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tag_);
      }
      if (!getCategoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, category_);
      }
      if (!getLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, label_);
      }
      if (breakLevel_ != syntaxnet.SentenceOuterClass.Token.BreakLevel.NO_BREAK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, breakLevel_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof syntaxnet.SentenceOuterClass.Token)) {
        return super.equals(obj);
      }
      syntaxnet.SentenceOuterClass.Token other = (syntaxnet.SentenceOuterClass.Token) obj;

      boolean result = true;
      result = result && getWord()
          .equals(other.getWord());
      result = result && (getStart()
          == other.getStart());
      result = result && (getEnd()
          == other.getEnd());
      result = result && (getHead()
          == other.getHead());
      result = result && getTag()
          .equals(other.getTag());
      result = result && getCategory()
          .equals(other.getCategory());
      result = result && getLabel()
          .equals(other.getLabel());
      result = result && breakLevel_ == other.breakLevel_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORD_FIELD_NUMBER;
      hash = (53 * hash) + getWord().hashCode();
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + getStart();
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + getEnd();
      hash = (37 * hash) + HEAD_FIELD_NUMBER;
      hash = (53 * hash) + getHead();
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTag().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      hash = (37 * hash) + BREAK_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + breakLevel_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static syntaxnet.SentenceOuterClass.Token parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static syntaxnet.SentenceOuterClass.Token parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static syntaxnet.SentenceOuterClass.Token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static syntaxnet.SentenceOuterClass.Token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static syntaxnet.SentenceOuterClass.Token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static syntaxnet.SentenceOuterClass.Token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static syntaxnet.SentenceOuterClass.Token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static syntaxnet.SentenceOuterClass.Token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static syntaxnet.SentenceOuterClass.Token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static syntaxnet.SentenceOuterClass.Token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static syntaxnet.SentenceOuterClass.Token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static syntaxnet.SentenceOuterClass.Token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(syntaxnet.SentenceOuterClass.Token prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A document token marks a span of bytes in the document text as a token
     * or word.
     * </pre>
     *
     * Protobuf type {@code syntaxnet.Token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:syntaxnet.Token)
        syntaxnet.SentenceOuterClass.TokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return syntaxnet.SentenceOuterClass.internal_static_syntaxnet_Token_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return syntaxnet.SentenceOuterClass.internal_static_syntaxnet_Token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                syntaxnet.SentenceOuterClass.Token.class, syntaxnet.SentenceOuterClass.Token.Builder.class);
      }

      // Construct using syntaxnet.SentenceOuterClass.Token.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        word_ = "";

        start_ = 0;

        end_ = 0;

        head_ = 0;

        tag_ = "";

        category_ = "";

        label_ = "";

        breakLevel_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return syntaxnet.SentenceOuterClass.internal_static_syntaxnet_Token_descriptor;
      }

      public syntaxnet.SentenceOuterClass.Token getDefaultInstanceForType() {
        return syntaxnet.SentenceOuterClass.Token.getDefaultInstance();
      }

      public syntaxnet.SentenceOuterClass.Token build() {
        syntaxnet.SentenceOuterClass.Token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public syntaxnet.SentenceOuterClass.Token buildPartial() {
        syntaxnet.SentenceOuterClass.Token result = new syntaxnet.SentenceOuterClass.Token(this);
        result.word_ = word_;
        result.start_ = start_;
        result.end_ = end_;
        result.head_ = head_;
        result.tag_ = tag_;
        result.category_ = category_;
        result.label_ = label_;
        result.breakLevel_ = breakLevel_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof syntaxnet.SentenceOuterClass.Token) {
          return mergeFrom((syntaxnet.SentenceOuterClass.Token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(syntaxnet.SentenceOuterClass.Token other) {
        if (other == syntaxnet.SentenceOuterClass.Token.getDefaultInstance()) return this;
        if (!other.getWord().isEmpty()) {
          word_ = other.word_;
          onChanged();
        }
        if (other.getStart() != 0) {
          setStart(other.getStart());
        }
        if (other.getEnd() != 0) {
          setEnd(other.getEnd());
        }
        if (other.getHead() != 0) {
          setHead(other.getHead());
        }
        if (!other.getTag().isEmpty()) {
          tag_ = other.tag_;
          onChanged();
        }
        if (!other.getCategory().isEmpty()) {
          category_ = other.category_;
          onChanged();
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          onChanged();
        }
        if (other.breakLevel_ != 0) {
          setBreakLevelValue(other.getBreakLevelValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        syntaxnet.SentenceOuterClass.Token parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (syntaxnet.SentenceOuterClass.Token) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object word_ = "";
      /**
       * <pre>
       * Token word form.
       * </pre>
       *
       * <code>string word = 1;</code>
       */
      public java.lang.String getWord() {
        java.lang.Object ref = word_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          word_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Token word form.
       * </pre>
       *
       * <code>string word = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWordBytes() {
        java.lang.Object ref = word_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          word_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Token word form.
       * </pre>
       *
       * <code>string word = 1;</code>
       */
      public Builder setWord(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        word_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Token word form.
       * </pre>
       *
       * <code>string word = 1;</code>
       */
      public Builder clearWord() {
        
        word_ = getDefaultInstance().getWord();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Token word form.
       * </pre>
       *
       * <code>string word = 1;</code>
       */
      public Builder setWordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        word_ = value;
        onChanged();
        return this;
      }

      private int start_ ;
      /**
       * <pre>
       * Start position of token in text.
       * </pre>
       *
       * <code>int32 start = 2;</code>
       */
      public int getStart() {
        return start_;
      }
      /**
       * <pre>
       * Start position of token in text.
       * </pre>
       *
       * <code>int32 start = 2;</code>
       */
      public Builder setStart(int value) {
        
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Start position of token in text.
       * </pre>
       *
       * <code>int32 start = 2;</code>
       */
      public Builder clearStart() {
        
        start_ = 0;
        onChanged();
        return this;
      }

      private int end_ ;
      /**
       * <pre>
       * End position of token in text. Gives index of last byte, not one past
       * the last byte. If token came from lexer, excludes any trailing HTML tags.
       * </pre>
       *
       * <code>int32 end = 3;</code>
       */
      public int getEnd() {
        return end_;
      }
      /**
       * <pre>
       * End position of token in text. Gives index of last byte, not one past
       * the last byte. If token came from lexer, excludes any trailing HTML tags.
       * </pre>
       *
       * <code>int32 end = 3;</code>
       */
      public Builder setEnd(int value) {
        
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * End position of token in text. Gives index of last byte, not one past
       * the last byte. If token came from lexer, excludes any trailing HTML tags.
       * </pre>
       *
       * <code>int32 end = 3;</code>
       */
      public Builder clearEnd() {
        
        end_ = 0;
        onChanged();
        return this;
      }

      private int head_ ;
      /**
       * <pre>
       * Head of this token in the dependency tree: the id of the token which has an
       * arc going to this one. If it is the root token of a sentence, then it is
       * set to -1.
       * </pre>
       *
       * <code>int32 head = 4;</code>
       */
      public int getHead() {
        return head_;
      }
      /**
       * <pre>
       * Head of this token in the dependency tree: the id of the token which has an
       * arc going to this one. If it is the root token of a sentence, then it is
       * set to -1.
       * </pre>
       *
       * <code>int32 head = 4;</code>
       */
      public Builder setHead(int value) {
        
        head_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Head of this token in the dependency tree: the id of the token which has an
       * arc going to this one. If it is the root token of a sentence, then it is
       * set to -1.
       * </pre>
       *
       * <code>int32 head = 4;</code>
       */
      public Builder clearHead() {
        
        head_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object tag_ = "";
      /**
       * <pre>
       * Part-of-speech tag for token.
       * </pre>
       *
       * <code>string tag = 5;</code>
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Part-of-speech tag for token.
       * </pre>
       *
       * <code>string tag = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Part-of-speech tag for token.
       * </pre>
       *
       * <code>string tag = 5;</code>
       */
      public Builder setTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Part-of-speech tag for token.
       * </pre>
       *
       * <code>string tag = 5;</code>
       */
      public Builder clearTag() {
        
        tag_ = getDefaultInstance().getTag();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Part-of-speech tag for token.
       * </pre>
       *
       * <code>string tag = 5;</code>
       */
      public Builder setTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tag_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <pre>
       * Coarse-grained word category for token.
       * </pre>
       *
       * <code>string category = 6;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Coarse-grained word category for token.
       * </pre>
       *
       * <code>string category = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Coarse-grained word category for token.
       * </pre>
       *
       * <code>string category = 6;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Coarse-grained word category for token.
       * </pre>
       *
       * <code>string category = 6;</code>
       */
      public Builder clearCategory() {
        
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Coarse-grained word category for token.
       * </pre>
       *
       * <code>string category = 6;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        category_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <pre>
       * Label for dependency relation between this token and its head.
       * </pre>
       *
       * <code>string label = 7;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Label for dependency relation between this token and its head.
       * </pre>
       *
       * <code>string label = 7;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Label for dependency relation between this token and its head.
       * </pre>
       *
       * <code>string label = 7;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Label for dependency relation between this token and its head.
       * </pre>
       *
       * <code>string label = 7;</code>
       */
      public Builder clearLabel() {
        
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Label for dependency relation between this token and its head.
       * </pre>
       *
       * <code>string label = 7;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        label_ = value;
        onChanged();
        return this;
      }

      private int breakLevel_ = 0;
      /**
       * <pre>
       *[default = SPACE_BREAK];
       * </pre>
       *
       * <code>.syntaxnet.Token.BreakLevel break_level = 8;</code>
       */
      public int getBreakLevelValue() {
        return breakLevel_;
      }
      /**
       * <pre>
       *[default = SPACE_BREAK];
       * </pre>
       *
       * <code>.syntaxnet.Token.BreakLevel break_level = 8;</code>
       */
      public Builder setBreakLevelValue(int value) {
        breakLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *[default = SPACE_BREAK];
       * </pre>
       *
       * <code>.syntaxnet.Token.BreakLevel break_level = 8;</code>
       */
      public syntaxnet.SentenceOuterClass.Token.BreakLevel getBreakLevel() {
        syntaxnet.SentenceOuterClass.Token.BreakLevel result = syntaxnet.SentenceOuterClass.Token.BreakLevel.valueOf(breakLevel_);
        return result == null ? syntaxnet.SentenceOuterClass.Token.BreakLevel.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *[default = SPACE_BREAK];
       * </pre>
       *
       * <code>.syntaxnet.Token.BreakLevel break_level = 8;</code>
       */
      public Builder setBreakLevel(syntaxnet.SentenceOuterClass.Token.BreakLevel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        breakLevel_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *[default = SPACE_BREAK];
       * </pre>
       *
       * <code>.syntaxnet.Token.BreakLevel break_level = 8;</code>
       */
      public Builder clearBreakLevel() {
        
        breakLevel_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:syntaxnet.Token)
    }

    // @@protoc_insertion_point(class_scope:syntaxnet.Token)
    private static final syntaxnet.SentenceOuterClass.Token DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new syntaxnet.SentenceOuterClass.Token();
    }

    public static syntaxnet.SentenceOuterClass.Token getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Token>
        PARSER = new com.google.protobuf.AbstractParser<Token>() {
      public Token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Token(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Token> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Token> getParserForType() {
      return PARSER;
    }

    public syntaxnet.SentenceOuterClass.Token getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_syntaxnet_Sentence_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_syntaxnet_Sentence_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_syntaxnet_Token_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_syntaxnet_Token_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016sentence.proto\022\tsyntaxnet\"H\n\010Sentence\022" +
      "\r\n\005docid\030\001 \001(\t\022\014\n\004text\030\002 \001(\t\022\037\n\005token\030\003 " +
      "\003(\0132\020.syntaxnet.Token\"\360\001\n\005Token\022\014\n\004word\030" +
      "\001 \001(\t\022\r\n\005start\030\002 \001(\005\022\013\n\003end\030\003 \001(\005\022\014\n\004hea" +
      "d\030\004 \001(\005\022\013\n\003tag\030\005 \001(\t\022\020\n\010category\030\006 \001(\t\022\r" +
      "\n\005label\030\007 \001(\t\0220\n\013break_level\030\010 \001(\0162\033.syn" +
      "taxnet.Token.BreakLevel\"O\n\nBreakLevel\022\014\n" +
      "\010NO_BREAK\020\000\022\017\n\013SPACE_BREAK\020\001\022\016\n\nLINE_BRE" +
      "AK\020\002\022\022\n\016SENTENCE_BREAK\020\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_syntaxnet_Sentence_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_syntaxnet_Sentence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_syntaxnet_Sentence_descriptor,
        new java.lang.String[] { "Docid", "Text", "Token", });
    internal_static_syntaxnet_Token_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_syntaxnet_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_syntaxnet_Token_descriptor,
        new java.lang.String[] { "Word", "Start", "End", "Head", "Tag", "Category", "Label", "BreakLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
